#!/bin/bash

if [ -e /root/hash.md5 ]
then
    if ! md5sum -c /root/hash.md5
    then
	echo "Hash sum didn't match with previous value" | mail -s "Didn't match" root
	md5sum /etc/crontab > /root/hash.md5
    fi
else
    md5sum /etc/crontab > /root/hash.md5
fi
